#pragma once

#define WIBO_SOFTWARE_CAPTURE_CONTEXT 0
#define WIBO_SOFTWARE_CAPTURE_LOCAL_RECORD 1232
#define WIBO_SOFTWARE_CAPTURE_RECORD 1384
#define WIBO_SOFTWARE_CAPTURE_CALLER 1392
#define WIBO_SOFTWARE_CAPTURE_SIZE 1408

#define WIBO_SOFTWARE_FRAME_CAPTURE 32
#define WIBO_SOFTWARE_FRAME_TEB (WIBO_SOFTWARE_FRAME_CAPTURE + WIBO_SOFTWARE_CAPTURE_SIZE)
#define WIBO_SOFTWARE_FRAME_SIZE 1456
