#pragma once

#include "software_exception_capture_offsets.h"

#define WIBO_TARGET_UNWIND_FRAME_OUTPUT WIBO_SOFTWARE_FRAME_SIZE
#define WIBO_TARGET_UNWIND_OUTPUT_SIZE 4064
#define WIBO_TARGET_UNWIND_CONTEXT_OFFSET 2640
#define WIBO_TARGET_UNWIND_FRAME_SIZE 5520
